namespace PIM_API.Migrations;

// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using PIM_API.Data;

#nullable disable

[DbContext(typeof(PriceAPIDbContext))]
partial class PriceAPIDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "7.0.12")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("PIM_API.Models.Item", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ItemName")
                    .IsRequired()
                    .HasColumnType("nvarchar(50)");

                b.Property<double>("ItemRetailPrice")
                    .HasColumnType("float");

                b.HasKey("Id");

                b.HasIndex("ItemName")
                    .IsUnique();

                b.ToTable("Items");
            });
#pragma warning restore 612, 618
    }
}
